{
 "title": "Work Drilldown",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES WITH KEY = \"provisionerId\" WHERE \"provisionerId\" !~ /^(bitbar|gce|deepspeech-provisioner|proj-servo)$/"
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES WITH KEY = \"workerType\" WHERE \"provisionerId\" = $provisioner"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "$provisioner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "provisioner" },
  {
   "title": "queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE $timeFilter AND \"provisionerId\" =~ /^$provisioner$/ GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "workers",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 13, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT LAST(\"pendingTasks\") AS \"queue\", LAST(\"running\") AS \"running\", LAST(\"idle\") AS \"idle\", LAST(\"workers\") AS \"workers\", (LAST(\"pendingTasks\") / LAST(\"workers\")) * (MEAN(\"idle\") / LAST(\"workers\")) AS \"lazy\", LAST(\"quarantined\") AS \"quarantined\", LAST(\"quarantined\") / LAST(\"workers\") AS \"percent quarantined\" FROM \"tc_queue2_exec\" WHERE (\"workerType\" =~ /^$workerType$/ AND \"provisionerId\" =~ /^$provisioner$/) AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" }
      ],
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "queue 1 week ago",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE $timeFilter AND \"provisionerId\" =~ /^$provisioner$/ GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"workers\") AS total, mean(\"idle\") AS idle, mean(\"running\") AS running FROM \"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($interval), \"provisionerId\", \"workerType\"",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"quarantinedWorkers\") AS \"quarantined\" FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($interval), \"provisionerId\", \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "quarantined" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  { "title": "$provisioner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE $timeFilter AND \"provisionerId\" =~ /^$provisioner$/ GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "workers",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 13, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT LAST(\"pendingTasks\") AS \"queue\", LAST(\"running\") AS \"running\", LAST(\"idle\") AS \"idle\", LAST(\"workers\") AS \"workers\", (LAST(\"pendingTasks\") / LAST(\"workers\")) * (MEAN(\"idle\") / LAST(\"workers\")) AS \"lazy\", LAST(\"quarantined\") AS \"quarantined\", LAST(\"quarantined\") / LAST(\"workers\") AS \"percent quarantined\" FROM \"tc_queue2_exec\" WHERE (\"workerType\" =~ /^$workerType$/ AND \"provisionerId\" =~ /^$provisioner$/) AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" }
      ],
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "queue 1 week ago",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE $timeFilter AND \"provisionerId\" =~ /^$provisioner$/ GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"workers\") AS total, mean(\"idle\") AS idle, mean(\"running\") AS running FROM \"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($interval), \"provisionerId\", \"workerType\"",
     "select": [
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"quarantinedWorkers\") AS \"quarantined\" FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($interval), \"provisionerId\", \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "quarantined" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  }
 ]
}