{
 "title": "Workers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM tc_queue_exec WITH KEY = \"provisionerId\""
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM tc_queue_exec WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/"
   }
  ]
 },
 "panels": [
  {
   "title": "Task Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "failed" ], "type": "alias" }
      ],
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "exception" ], "type": "alias" }
      ],
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "completed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "workers",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT LAST(\"pendingTasks\") AS \"queue\", LAST(\"running\") AS \"running\", LAST(\"idle\") AS \"idle\", LAST(\"workers\") AS \"workers\", (LAST(\"pendingTasks\") / LAST(\"workers\")) * (MEAN(\"idle\") / LAST(\"workers\")) AS \"lazy\", LAST(\"quarantined\") AS \"quarantined\", LAST(\"quarantined\") / LAST(\"workers\") AS \"percent quarantined\", mean(\"exception\") AS \"exception\", mean(\"failed\") AS \"failed\", mean(\"completed\") AS \"success\", 1.0 - mean(\"completed\") / (mean(\"exception\") + mean(\"failed\") + mean(\"completed\")) as \"percent failed\" FROM \"tc_queue2_exec\" WHERE \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" =~ /^$provisioner$/ AND $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" }
      ],
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "Running vs Active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "aws-provisionerhttp",
     "select": [
      [
       { "params": [ "runningCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "requestedCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "requested" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "pending" ], "type": "alias" }
      ],
      [
       { "params": [ "maxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"running\") AS \"active\", (mean(\"workers\") - mean(\"quarantined\")) AS \"running\", mean(\"quarantined\") AS \"quarantined\" FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" = 'releng-hardware') AND $timeFilter GROUP BY time($__interval * 10), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "!=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "queued tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  }
 ]
}